/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentTypesRouteImport } from './routes/admin.content-types'
import { Route as AdminGenerateRouteImport } from './routes/admin.generate'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNichesRouteImport } from './routes/admin.niches'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPillarsRouteImport } from './routes/admin.pillars'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPseoDashboardRouteImport } from './routes/admin.pseo-dashboard'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin.site-settings'
import { Route as AdminWidgetsRouteImport } from './routes/admin.widgets'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as NewsletterConfirmedRouteImport } from './routes/newsletter.confirmed'
import { Route as NewsletterInvalidRouteImport } from './routes/newsletter.invalid'
import { Route as NewsletterUnsubscribedRouteImport } from './routes/newsletter.unsubscribed'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as AdminContentTypesNewRouteImport } from './routes/admin.content-types.new'
import { Route as AdminPillarsNewRouteImport } from './routes/admin.pillars.new'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as ResourcesContentTypeIndexRouteImport } from './routes/resources.$contentType.index'
import { Route as ResourcesContentTypePageSlugRouteImport } from './routes/resources.$contentType.$pageSlug'
import { Route as AdminContentTypesIdEditRouteImport } from './routes/admin.content-types.$id.edit'
import { Route as AdminPagesIdEditRouteImport } from './routes/admin.pages.$id.edit'
import { Route as AdminPillarsIdEditRouteImport } from './routes/admin.pillars.$id.edit'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'
import { Route as ApiPublicNewsletterConfirmRouteImport } from './routes/api/public/newsletter/confirm'
import { Route as ApiPublicNewsletterUnsubscribeRouteImport } from './routes/api/public/newsletter/unsubscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTypesRoute = AdminContentTypesRouteImport.update({
  id: '/content-types',
  path: '/content-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerateRoute = AdminGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNichesRoute = AdminNichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPillarsRoute = AdminPillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPseoDashboardRoute = AdminPseoDashboardRouteImport.update({
  id: '/pseo-dashboard',
  path: '/pseo-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWidgetsRoute = AdminWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AdminRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmedRoute = NewsletterConfirmedRouteImport.update({
  id: '/newsletter/confirmed',
  path: '/newsletter/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterInvalidRoute = NewsletterInvalidRouteImport.update({
  id: '/newsletter/invalid',
  path: '/newsletter/invalid',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribedRoute = NewsletterUnsubscribedRouteImport.update({
  id: '/newsletter/unsubscribed',
  path: '/newsletter/unsubscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentTypesNewRoute = AdminContentTypesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContentTypesRoute,
} as any)
const AdminPillarsNewRoute = AdminPillarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPillarsRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const ResourcesContentTypeIndexRoute =
  ResourcesContentTypeIndexRouteImport.update({
    id: '/resources/$contentType/',
    path: '/resources/$contentType/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesContentTypePageSlugRoute =
  ResourcesContentTypePageSlugRouteImport.update({
    id: '/resources/$contentType/$pageSlug',
    path: '/resources/$contentType/$pageSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentTypesIdEditRoute = AdminContentTypesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminContentTypesRoute,
} as any)
const AdminPagesIdEditRoute = AdminPagesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminPillarsIdEditRoute = AdminPillarsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPillarsRoute,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPostsRoute,
} as any)
const ApiPublicNewsletterConfirmRoute =
  ApiPublicNewsletterConfirmRouteImport.update({
    id: '/api/public/newsletter/confirm',
    path: '/api/public/newsletter/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterUnsubscribeRoute =
  ApiPublicNewsletterUnsubscribeRouteImport.update({
    id: '/api/public/newsletter/unsubscribe',
    path: '/api/public/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content-types': typeof AdminContentTypesRouteWithChildren
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/pillars': typeof AdminPillarsRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/resources/$contentType/': typeof ResourcesContentTypeIndexRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content-types': typeof AdminContentTypesRouteWithChildren
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/pillars': typeof AdminPillarsRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/news': typeof NewsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/resources/$contentType': typeof ResourcesContentTypeIndexRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content-types': typeof AdminContentTypesRouteWithChildren
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/pillars': typeof AdminPillarsRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/resources/$contentType/': typeof ResourcesContentTypeIndexRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/content-types'
    | '/admin/generate'
    | '/admin/library'
    | '/admin/login'
    | '/admin/niches'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/posts'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/admin/'
    | '/blog/'
    | '/news/'
    | '/resources/'
    | '/admin/content-types/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/resources/$contentType/$pageSlug'
    | '/resources/$contentType/'
    | '/admin/content-types/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/content-types'
    | '/admin/generate'
    | '/admin/library'
    | '/admin/login'
    | '/admin/niches'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/posts'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/admin'
    | '/blog'
    | '/news'
    | '/resources'
    | '/admin/content-types/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/resources/$contentType/$pageSlug'
    | '/resources/$contentType'
    | '/admin/content-types/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/rss.xml'
    | '/sitemap'
    | '/sitemap.xml'
    | '/admin/categories'
    | '/admin/content-types'
    | '/admin/generate'
    | '/admin/library'
    | '/admin/login'
    | '/admin/niches'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/posts'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/admin/'
    | '/blog/'
    | '/news/'
    | '/resources/'
    | '/admin/content-types/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/resources/$contentType/$pageSlug'
    | '/resources/$contentType/'
    | '/admin/content-types/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  NewsIdRoute: typeof NewsIdRoute
  NewsletterConfirmedRoute: typeof NewsletterConfirmedRoute
  NewsletterInvalidRoute: typeof NewsletterInvalidRoute
  NewsletterUnsubscribedRoute: typeof NewsletterUnsubscribedRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ResourcesContentTypePageSlugRoute: typeof ResourcesContentTypePageSlugRoute
  ResourcesContentTypeIndexRoute: typeof ResourcesContentTypeIndexRoute
  ApiPublicNewsletterConfirmRoute: typeof ApiPublicNewsletterConfirmRoute
  ApiPublicNewsletterUnsubscribeRoute: typeof ApiPublicNewsletterUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-types': {
      id: '/admin/content-types'
      path: '/content-types'
      fullPath: '/admin/content-types'
      preLoaderRoute: typeof AdminContentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generate': {
      id: '/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AdminGenerateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/niches': {
      id: '/admin/niches'
      path: '/niches'
      fullPath: '/admin/niches'
      preLoaderRoute: typeof AdminNichesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pillars': {
      id: '/admin/pillars'
      path: '/pillars'
      fullPath: '/admin/pillars'
      preLoaderRoute: typeof AdminPillarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pseo-dashboard': {
      id: '/admin/pseo-dashboard'
      path: '/pseo-dashboard'
      fullPath: '/admin/pseo-dashboard'
      preLoaderRoute: typeof AdminPseoDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/widgets': {
      id: '/admin/widgets'
      path: '/widgets'
      fullPath: '/admin/widgets'
      preLoaderRoute: typeof AdminWidgetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirmed': {
      id: '/newsletter/confirmed'
      path: '/newsletter/confirmed'
      fullPath: '/newsletter/confirmed'
      preLoaderRoute: typeof NewsletterConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/invalid': {
      id: '/newsletter/invalid'
      path: '/newsletter/invalid'
      fullPath: '/newsletter/invalid'
      preLoaderRoute: typeof NewsletterInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribed': {
      id: '/newsletter/unsubscribed'
      path: '/newsletter/unsubscribed'
      fullPath: '/newsletter/unsubscribed'
      preLoaderRoute: typeof NewsletterUnsubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-types/new': {
      id: '/admin/content-types/new'
      path: '/new'
      fullPath: '/admin/content-types/new'
      preLoaderRoute: typeof AdminContentTypesNewRouteImport
      parentRoute: typeof AdminContentTypesRoute
    }
    '/admin/pillars/new': {
      id: '/admin/pillars/new'
      path: '/new'
      fullPath: '/admin/pillars/new'
      preLoaderRoute: typeof AdminPillarsNewRouteImport
      parentRoute: typeof AdminPillarsRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/resources/$contentType/': {
      id: '/resources/$contentType/'
      path: '/resources/$contentType'
      fullPath: '/resources/$contentType/'
      preLoaderRoute: typeof ResourcesContentTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$contentType/$pageSlug': {
      id: '/resources/$contentType/$pageSlug'
      path: '/resources/$contentType/$pageSlug'
      fullPath: '/resources/$contentType/$pageSlug'
      preLoaderRoute: typeof ResourcesContentTypePageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content-types/$id/edit': {
      id: '/admin/content-types/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/content-types/$id/edit'
      preLoaderRoute: typeof AdminContentTypesIdEditRouteImport
      parentRoute: typeof AdminContentTypesRoute
    }
    '/admin/pages/$id/edit': {
      id: '/admin/pages/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/pages/$id/edit'
      preLoaderRoute: typeof AdminPagesIdEditRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/pillars/$id/edit': {
      id: '/admin/pillars/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/pillars/$id/edit'
      preLoaderRoute: typeof AdminPillarsIdEditRouteImport
      parentRoute: typeof AdminPillarsRoute
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/api/public/newsletter/confirm': {
      id: '/api/public/newsletter/confirm'
      path: '/api/public/newsletter/confirm'
      fullPath: '/api/public/newsletter/confirm'
      preLoaderRoute: typeof ApiPublicNewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/unsubscribe': {
      id: '/api/public/newsletter/unsubscribe'
      path: '/api/public/newsletter/unsubscribe'
      fullPath: '/api/public/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiPublicNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminContentTypesRouteChildren {
  AdminContentTypesNewRoute: typeof AdminContentTypesNewRoute
  AdminContentTypesIdEditRoute: typeof AdminContentTypesIdEditRoute
}

const AdminContentTypesRouteChildren: AdminContentTypesRouteChildren = {
  AdminContentTypesNewRoute: AdminContentTypesNewRoute,
  AdminContentTypesIdEditRoute: AdminContentTypesIdEditRoute,
}

const AdminContentTypesRouteWithChildren =
  AdminContentTypesRoute._addFileChildren(AdminContentTypesRouteChildren)

interface AdminPagesRouteChildren {
  AdminPagesIdEditRoute: typeof AdminPagesIdEditRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesIdEditRoute: AdminPagesIdEditRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminPillarsRouteChildren {
  AdminPillarsNewRoute: typeof AdminPillarsNewRoute
  AdminPillarsIdEditRoute: typeof AdminPillarsIdEditRoute
}

const AdminPillarsRouteChildren: AdminPillarsRouteChildren = {
  AdminPillarsNewRoute: AdminPillarsNewRoute,
  AdminPillarsIdEditRoute: AdminPillarsIdEditRoute,
}

const AdminPillarsRouteWithChildren = AdminPillarsRoute._addFileChildren(
  AdminPillarsRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentTypesRoute: typeof AdminContentTypesRouteWithChildren
  AdminGenerateRoute: typeof AdminGenerateRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNichesRoute: typeof AdminNichesRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminPillarsRoute: typeof AdminPillarsRouteWithChildren
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminPseoDashboardRoute: typeof AdminPseoDashboardRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminWidgetsRoute: typeof AdminWidgetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentTypesRoute: AdminContentTypesRouteWithChildren,
  AdminGenerateRoute: AdminGenerateRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNichesRoute: AdminNichesRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminPillarsRoute: AdminPillarsRouteWithChildren,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminPseoDashboardRoute: AdminPseoDashboardRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminWidgetsRoute: AdminWidgetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  NewsIdRoute: NewsIdRoute,
  NewsletterConfirmedRoute: NewsletterConfirmedRoute,
  NewsletterInvalidRoute: NewsletterInvalidRoute,
  NewsletterUnsubscribedRoute: NewsletterUnsubscribedRoute,
  BlogIndexRoute: BlogIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ResourcesContentTypePageSlugRoute: ResourcesContentTypePageSlugRoute,
  ResourcesContentTypeIndexRoute: ResourcesContentTypeIndexRoute,
  ApiPublicNewsletterConfirmRoute: ApiPublicNewsletterConfirmRoute,
  ApiPublicNewsletterUnsubscribeRoute: ApiPublicNewsletterUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
