/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentTypesRouteImport } from './routes/admin.content-types'
import { Route as AdminGenerateRouteImport } from './routes/admin.generate'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNichesRouteImport } from './routes/admin.niches'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPillarsRouteImport } from './routes/admin.pillars'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPseoDashboardRouteImport } from './routes/admin.pseo-dashboard'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin.site-settings'
import { Route as AdminWidgetsRouteImport } from './routes/admin.widgets'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as NewsletterConfirmedRouteImport } from './routes/newsletter.confirmed'
import { Route as NewsletterInvalidRouteImport } from './routes/newsletter.invalid'
import { Route as NewsletterUnsubscribedRouteImport } from './routes/newsletter.unsubscribed'
import { Route as ResourcesContentTypeRouteImport } from './routes/resources.$contentType'
import { Route as AdminContentTypesNewRouteImport } from './routes/admin.content-types.new'
import { Route as AdminPillarsNewRouteImport } from './routes/admin.pillars.new'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as ResourcesContentTypePageSlugRouteImport } from './routes/resources.$contentType.$pageSlug'
import { Route as AdminContentTypesIdEditRouteImport } from './routes/admin.content-types.$id.edit'
import { Route as AdminPagesIdEditRouteImport } from './routes/admin.pages.$id.edit'
import { Route as AdminPillarsIdEditRouteImport } from './routes/admin.pillars.$id.edit'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTypesRoute = AdminContentTypesRouteImport.update({
  id: '/content-types',
  path: '/content-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerateRoute = AdminGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNichesRoute = AdminNichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPillarsRoute = AdminPillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPseoDashboardRoute = AdminPseoDashboardRouteImport.update({
  id: '/pseo-dashboard',
  path: '/pseo-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWidgetsRoute = AdminWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const NewsletterConfirmedRoute = NewsletterConfirmedRouteImport.update({
  id: '/newsletter/confirmed',
  path: '/newsletter/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterInvalidRoute = NewsletterInvalidRouteImport.update({
  id: '/newsletter/invalid',
  path: '/newsletter/invalid',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribedRoute = NewsletterUnsubscribedRouteImport.update({
  id: '/newsletter/unsubscribed',
  path: '/newsletter/unsubscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesContentTypeRoute = ResourcesContentTypeRouteImport.update({
  id: '/$contentType',
  path: '/$contentType',
  getParentRoute: () => ResourcesRoute,
} as any)
const AdminContentTypesNewRoute = AdminContentTypesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContentTypesRoute,
} as any)
const AdminPillarsNewRoute = AdminPillarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPillarsRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminPostsRoute,
} as any)
const ResourcesContentTypePageSlugRoute =
  ResourcesContentTypePageSlugRouteImport.update({
    id: '/$pageSlug',
    path: '/$pageSlug',
    getParentRoute: () => ResourcesContentTypeRoute,
  } as any)
const AdminContentTypesIdEditRoute = AdminContentTypesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminContentTypesRoute,
} as any)
const AdminPagesIdEditRoute = AdminPagesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminPillarsIdEditRoute = AdminPillarsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPillarsRoute,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminPostsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content-types': typeof AdminContentTypesRouteWithChildren
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/pillars': typeof AdminPillarsRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/resources/$contentType': typeof ResourcesContentTypeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content-types': typeof AdminContentTypesRouteWithChildren
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/pillars': typeof AdminPillarsRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/resources/$contentType': typeof ResourcesContentTypeRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content-types': typeof AdminContentTypesRouteWithChildren
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/pillars': typeof AdminPillarsRouteWithChildren
  '/admin/posts': typeof AdminPostsRouteWithChildren
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/resources/$contentType': typeof ResourcesContentTypeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/news'
    | '/resources'
    | '/sitemap'
    | '/admin/categories'
    | '/admin/content-types'
    | '/admin/generate'
    | '/admin/library'
    | '/admin/login'
    | '/admin/niches'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/posts'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/resources/$contentType'
    | '/admin/'
    | '/admin/content-types/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/resources/$contentType/$pageSlug'
    | '/admin/content-types/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/news'
    | '/resources'
    | '/sitemap'
    | '/admin/categories'
    | '/admin/content-types'
    | '/admin/generate'
    | '/admin/library'
    | '/admin/login'
    | '/admin/niches'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/posts'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/resources/$contentType'
    | '/admin'
    | '/admin/content-types/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/resources/$contentType/$pageSlug'
    | '/admin/content-types/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/news'
    | '/resources'
    | '/sitemap'
    | '/admin/categories'
    | '/admin/content-types'
    | '/admin/generate'
    | '/admin/library'
    | '/admin/login'
    | '/admin/niches'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/posts'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/resources/$contentType'
    | '/admin/'
    | '/admin/content-types/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/resources/$contentType/$pageSlug'
    | '/admin/content-types/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapRoute: typeof SitemapRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  NewsletterConfirmedRoute: typeof NewsletterConfirmedRoute
  NewsletterInvalidRoute: typeof NewsletterInvalidRoute
  NewsletterUnsubscribedRoute: typeof NewsletterUnsubscribedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-types': {
      id: '/admin/content-types'
      path: '/content-types'
      fullPath: '/admin/content-types'
      preLoaderRoute: typeof AdminContentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generate': {
      id: '/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AdminGenerateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/niches': {
      id: '/admin/niches'
      path: '/niches'
      fullPath: '/admin/niches'
      preLoaderRoute: typeof AdminNichesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pillars': {
      id: '/admin/pillars'
      path: '/pillars'
      fullPath: '/admin/pillars'
      preLoaderRoute: typeof AdminPillarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pseo-dashboard': {
      id: '/admin/pseo-dashboard'
      path: '/pseo-dashboard'
      fullPath: '/admin/pseo-dashboard'
      preLoaderRoute: typeof AdminPseoDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/widgets': {
      id: '/admin/widgets'
      path: '/widgets'
      fullPath: '/admin/widgets'
      preLoaderRoute: typeof AdminWidgetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/newsletter/confirmed': {
      id: '/newsletter/confirmed'
      path: '/newsletter/confirmed'
      fullPath: '/newsletter/confirmed'
      preLoaderRoute: typeof NewsletterConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/invalid': {
      id: '/newsletter/invalid'
      path: '/newsletter/invalid'
      fullPath: '/newsletter/invalid'
      preLoaderRoute: typeof NewsletterInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribed': {
      id: '/newsletter/unsubscribed'
      path: '/newsletter/unsubscribed'
      fullPath: '/newsletter/unsubscribed'
      preLoaderRoute: typeof NewsletterUnsubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$contentType': {
      id: '/resources/$contentType'
      path: '/$contentType'
      fullPath: '/resources/$contentType'
      preLoaderRoute: typeof ResourcesContentTypeRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/admin/content-types/new': {
      id: '/admin/content-types/new'
      path: '/new'
      fullPath: '/admin/content-types/new'
      preLoaderRoute: typeof AdminContentTypesNewRouteImport
      parentRoute: typeof AdminContentTypesRoute
    }
    '/admin/pillars/new': {
      id: '/admin/pillars/new'
      path: '/new'
      fullPath: '/admin/pillars/new'
      preLoaderRoute: typeof AdminPillarsNewRouteImport
      parentRoute: typeof AdminPillarsRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminPostsRoute
    }
    '/resources/$contentType/$pageSlug': {
      id: '/resources/$contentType/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/resources/$contentType/$pageSlug'
      preLoaderRoute: typeof ResourcesContentTypePageSlugRouteImport
      parentRoute: typeof ResourcesContentTypeRoute
    }
    '/admin/content-types/$id/edit': {
      id: '/admin/content-types/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/content-types/$id/edit'
      preLoaderRoute: typeof AdminContentTypesIdEditRouteImport
      parentRoute: typeof AdminContentTypesRoute
    }
    '/admin/pages/$id/edit': {
      id: '/admin/pages/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/pages/$id/edit'
      preLoaderRoute: typeof AdminPagesIdEditRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/pillars/$id/edit': {
      id: '/admin/pillars/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/pillars/$id/edit'
      preLoaderRoute: typeof AdminPillarsIdEditRouteImport
      parentRoute: typeof AdminPillarsRoute
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminPostsRoute
    }
  }
}

interface AdminContentTypesRouteChildren {
  AdminContentTypesNewRoute: typeof AdminContentTypesNewRoute
  AdminContentTypesIdEditRoute: typeof AdminContentTypesIdEditRoute
}

const AdminContentTypesRouteChildren: AdminContentTypesRouteChildren = {
  AdminContentTypesNewRoute: AdminContentTypesNewRoute,
  AdminContentTypesIdEditRoute: AdminContentTypesIdEditRoute,
}

const AdminContentTypesRouteWithChildren =
  AdminContentTypesRoute._addFileChildren(AdminContentTypesRouteChildren)

interface AdminPagesRouteChildren {
  AdminPagesIdEditRoute: typeof AdminPagesIdEditRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesIdEditRoute: AdminPagesIdEditRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminPillarsRouteChildren {
  AdminPillarsNewRoute: typeof AdminPillarsNewRoute
  AdminPillarsIdEditRoute: typeof AdminPillarsIdEditRoute
}

const AdminPillarsRouteChildren: AdminPillarsRouteChildren = {
  AdminPillarsNewRoute: AdminPillarsNewRoute,
  AdminPillarsIdEditRoute: AdminPillarsIdEditRoute,
}

const AdminPillarsRouteWithChildren = AdminPillarsRoute._addFileChildren(
  AdminPillarsRouteChildren,
)

interface AdminPostsRouteChildren {
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

const AdminPostsRouteChildren: AdminPostsRouteChildren = {
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}

const AdminPostsRouteWithChildren = AdminPostsRoute._addFileChildren(
  AdminPostsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentTypesRoute: typeof AdminContentTypesRouteWithChildren
  AdminGenerateRoute: typeof AdminGenerateRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNichesRoute: typeof AdminNichesRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminPillarsRoute: typeof AdminPillarsRouteWithChildren
  AdminPostsRoute: typeof AdminPostsRouteWithChildren
  AdminPseoDashboardRoute: typeof AdminPseoDashboardRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminWidgetsRoute: typeof AdminWidgetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentTypesRoute: AdminContentTypesRouteWithChildren,
  AdminGenerateRoute: AdminGenerateRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNichesRoute: AdminNichesRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminPillarsRoute: AdminPillarsRouteWithChildren,
  AdminPostsRoute: AdminPostsRouteWithChildren,
  AdminPseoDashboardRoute: AdminPseoDashboardRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminWidgetsRoute: AdminWidgetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ResourcesContentTypeRouteChildren {
  ResourcesContentTypePageSlugRoute: typeof ResourcesContentTypePageSlugRoute
}

const ResourcesContentTypeRouteChildren: ResourcesContentTypeRouteChildren = {
  ResourcesContentTypePageSlugRoute: ResourcesContentTypePageSlugRoute,
}

const ResourcesContentTypeRouteWithChildren =
  ResourcesContentTypeRoute._addFileChildren(ResourcesContentTypeRouteChildren)

interface ResourcesRouteChildren {
  ResourcesContentTypeRoute: typeof ResourcesContentTypeRouteWithChildren
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesContentTypeRoute: ResourcesContentTypeRouteWithChildren,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapRoute: SitemapRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  NewsletterConfirmedRoute: NewsletterConfirmedRoute,
  NewsletterInvalidRoute: NewsletterInvalidRoute,
  NewsletterUnsubscribedRoute: NewsletterUnsubscribedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
