/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OfferAccessRouteImport } from './routes/offer-access'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as StartHereRouteImport } from './routes/start-here'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAudienceRouteImport } from './routes/admin.audience'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminConversionsRouteImport } from './routes/admin.conversions'
import { Route as AdminGenerateRouteImport } from './routes/admin.generate'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminNichesRouteImport } from './routes/admin.niches'
import { Route as AdminPseoDashboardRouteImport } from './routes/admin.pseo-dashboard'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin.site-settings'
import { Route as AdminWidgetsRouteImport } from './routes/admin.widgets'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminResetPasswordRouteImport } from './routes/admin_.reset-password'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as NewsletterConfirmedRouteImport } from './routes/newsletter.confirmed'
import { Route as NewsletterInvalidRouteImport } from './routes/newsletter.invalid'
import { Route as NewsletterUnsubscribedRouteImport } from './routes/newsletter.unsubscribed'
import { Route as OffersSlugRouteImport } from './routes/offers.$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesContentTypeRouteImport } from './routes/resources.$contentType'
import { Route as AdminContentTypesIndexRouteImport } from './routes/admin.content-types.index'
import { Route as AdminContentTypesNewRouteImport } from './routes/admin.content-types.new'
import { Route as AdminOffersIndexRouteImport } from './routes/admin.offers.index'
import { Route as AdminOffersNewRouteImport } from './routes/admin.offers.new'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminPillarsIndexRouteImport } from './routes/admin.pillars.index'
import { Route as AdminPillarsNewRouteImport } from './routes/admin.pillars.new'
import { Route as AdminPostsIndexRouteImport } from './routes/admin.posts.index'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as ApiAdminOfferCopyRouteImport } from './routes/api/admin/offer-copy'
import { Route as OffersPreviewIdRouteImport } from './routes/offers.preview.$id'
import { Route as ResourcesContentTypeIndexRouteImport } from './routes/resources.$contentType.index'
import { Route as ResourcesContentTypePageSlugRouteImport } from './routes/resources.$contentType.$pageSlug'
import { Route as AdminContentTypesIdEditRouteImport } from './routes/admin.content-types.$id.edit'
import { Route as AdminOffersIdEditRouteImport } from './routes/admin.offers.$id.edit'
import { Route as AdminPagesIdEditRouteImport } from './routes/admin.pages.$id.edit'
import { Route as AdminPillarsIdEditRouteImport } from './routes/admin.pillars.$id.edit'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'
import { Route as ApiPublicNewsletterConfirmRouteImport } from './routes/api/public/newsletter/confirm'
import { Route as ApiPublicNewsletterUnsubscribeRouteImport } from './routes/api/public/newsletter/unsubscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferAccessRoute = OfferAccessRouteImport.update({
  id: '/offer-access',
  path: '/offer-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const StartHereRoute = StartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudienceRoute = AdminAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversionsRoute = AdminConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerateRoute = AdminGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNichesRoute = AdminNichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPseoDashboardRoute = AdminPseoDashboardRouteImport.update({
  id: '/pseo-dashboard',
  path: '/pseo-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWidgetsRoute = AdminWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin_/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const NewsletterConfirmedRoute = NewsletterConfirmedRouteImport.update({
  id: '/newsletter/confirmed',
  path: '/newsletter/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterInvalidRoute = NewsletterInvalidRouteImport.update({
  id: '/newsletter/invalid',
  path: '/newsletter/invalid',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterUnsubscribedRoute = NewsletterUnsubscribedRouteImport.update({
  id: '/newsletter/unsubscribed',
  path: '/newsletter/unsubscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesContentTypeRoute = ResourcesContentTypeRouteImport.update({
  id: '/$contentType',
  path: '/$contentType',
  getParentRoute: () => ResourcesRoute,
} as any)
const AdminContentTypesIndexRoute = AdminContentTypesIndexRouteImport.update({
  id: '/content-types/',
  path: '/content-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTypesNewRoute = AdminContentTypesNewRouteImport.update({
  id: '/content-types/new',
  path: '/content-types/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersIndexRoute = AdminOffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersNewRoute = AdminOffersNewRouteImport.update({
  id: '/offers/new',
  path: '/offers/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPillarsIndexRoute = AdminPillarsIndexRouteImport.update({
  id: '/pillars/',
  path: '/pillars/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPillarsNewRoute = AdminPillarsNewRouteImport.update({
  id: '/pillars/new',
  path: '/pillars/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminOfferCopyRoute = ApiAdminOfferCopyRouteImport.update({
  id: '/api/admin/offer-copy',
  path: '/api/admin/offer-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersPreviewIdRoute = OffersPreviewIdRouteImport.update({
  id: '/offers/preview/$id',
  path: '/offers/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesContentTypeIndexRoute =
  ResourcesContentTypeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ResourcesContentTypeRoute,
  } as any)
const ResourcesContentTypePageSlugRoute =
  ResourcesContentTypePageSlugRouteImport.update({
    id: '/$pageSlug',
    path: '/$pageSlug',
    getParentRoute: () => ResourcesContentTypeRoute,
  } as any)
const AdminContentTypesIdEditRoute = AdminContentTypesIdEditRouteImport.update({
  id: '/content-types/$id/edit',
  path: '/content-types/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersIdEditRoute = AdminOffersIdEditRouteImport.update({
  id: '/offers/$id/edit',
  path: '/offers/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesIdEditRoute = AdminPagesIdEditRouteImport.update({
  id: '/pages/$id/edit',
  path: '/pages/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPillarsIdEditRoute = AdminPillarsIdEditRouteImport.update({
  id: '/pillars/$id/edit',
  path: '/pillars/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/posts/$id/edit',
  path: '/posts/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicNewsletterConfirmRoute =
  ApiPublicNewsletterConfirmRouteImport.update({
    id: '/api/public/newsletter/confirm',
    path: '/api/public/newsletter/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterUnsubscribeRoute =
  ApiPublicNewsletterUnsubscribeRouteImport.update({
    id: '/api/public/newsletter/unsubscribe',
    path: '/api/public/newsletter/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/news': typeof NewsRouteWithChildren
  '/offer-access': typeof OfferAccessRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/shop': typeof ShopRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/start-here': typeof StartHereRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/audience': typeof AdminAudienceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/conversions': typeof AdminConversionsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/resources/$contentType': typeof ResourcesContentTypeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin/offer-copy': typeof ApiAdminOfferCopyRoute
  '/offers/preview/$id': typeof OffersPreviewIdRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/admin/content-types/': typeof AdminContentTypesIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/pillars/': typeof AdminPillarsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/resources/$contentType/': typeof ResourcesContentTypeIndexRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/offers/$id/edit': typeof AdminOffersIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/offer-access': typeof OfferAccessRoute
  '/privacy': typeof PrivacyRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/shop': typeof ShopRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/start-here': typeof StartHereRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/audience': typeof AdminAudienceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/conversions': typeof AdminConversionsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/news': typeof NewsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin/offer-copy': typeof ApiAdminOfferCopyRoute
  '/offers/preview/$id': typeof OffersPreviewIdRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/admin/content-types': typeof AdminContentTypesIndexRoute
  '/admin/offers': typeof AdminOffersIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/pillars': typeof AdminPillarsIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/resources/$contentType': typeof ResourcesContentTypeIndexRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/offers/$id/edit': typeof AdminOffersIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/news': typeof NewsRouteWithChildren
  '/offer-access': typeof OfferAccessRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/rss.xml': typeof RssDotxmlRoute
  '/shop': typeof ShopRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/start-here': typeof StartHereRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/audience': typeof AdminAudienceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/conversions': typeof AdminConversionsRoute
  '/admin/generate': typeof AdminGenerateRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/niches': typeof AdminNichesRoute
  '/admin/pseo-dashboard': typeof AdminPseoDashboardRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin_/reset-password': typeof AdminResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/news/$id': typeof NewsIdRoute
  '/newsletter/confirmed': typeof NewsletterConfirmedRoute
  '/newsletter/invalid': typeof NewsletterInvalidRoute
  '/newsletter/unsubscribed': typeof NewsletterUnsubscribedRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/resources/$contentType': typeof ResourcesContentTypeRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/admin/content-types/new': typeof AdminContentTypesNewRoute
  '/admin/offers/new': typeof AdminOffersNewRoute
  '/admin/pillars/new': typeof AdminPillarsNewRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/admin/offer-copy': typeof ApiAdminOfferCopyRoute
  '/offers/preview/$id': typeof OffersPreviewIdRoute
  '/resources/$contentType/$pageSlug': typeof ResourcesContentTypePageSlugRoute
  '/admin/content-types/': typeof AdminContentTypesIndexRoute
  '/admin/offers/': typeof AdminOffersIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/pillars/': typeof AdminPillarsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/resources/$contentType/': typeof ResourcesContentTypeIndexRoute
  '/admin/content-types/$id/edit': typeof AdminContentTypesIdEditRoute
  '/admin/offers/$id/edit': typeof AdminOffersIdEditRoute
  '/admin/pages/$id/edit': typeof AdminPagesIdEditRoute
  '/admin/pillars/$id/edit': typeof AdminPillarsIdEditRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
  '/api/public/newsletter/confirm': typeof ApiPublicNewsletterConfirmRoute
  '/api/public/newsletter/unsubscribe': typeof ApiPublicNewsletterUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/news'
    | '/offer-access'
    | '/privacy'
    | '/resources'
    | '/rss.xml'
    | '/shop'
    | '/sitemap'
    | '/sitemap.xml'
    | '/speaking'
    | '/start-here'
    | '/support'
    | '/terms'
    | '/admin/audience'
    | '/admin/categories'
    | '/admin/conversions'
    | '/admin/generate'
    | '/admin/inquiries'
    | '/admin/library'
    | '/admin/niches'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/admin/login'
    | '/admin/reset-password'
    | '/api/chat'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/offers/$slug'
    | '/resources/$contentType'
    | '/admin/'
    | '/blog/'
    | '/news/'
    | '/resources/'
    | '/admin/content-types/new'
    | '/admin/offers/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/api/admin/offer-copy'
    | '/offers/preview/$id'
    | '/resources/$contentType/$pageSlug'
    | '/admin/content-types/'
    | '/admin/offers/'
    | '/admin/pages/'
    | '/admin/pillars/'
    | '/admin/posts/'
    | '/resources/$contentType/'
    | '/admin/content-types/$id/edit'
    | '/admin/offers/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/offer-access'
    | '/privacy'
    | '/rss.xml'
    | '/shop'
    | '/sitemap'
    | '/sitemap.xml'
    | '/speaking'
    | '/start-here'
    | '/support'
    | '/terms'
    | '/admin/audience'
    | '/admin/categories'
    | '/admin/conversions'
    | '/admin/generate'
    | '/admin/inquiries'
    | '/admin/library'
    | '/admin/niches'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/admin/login'
    | '/admin/reset-password'
    | '/api/chat'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/offers/$slug'
    | '/admin'
    | '/blog'
    | '/news'
    | '/resources'
    | '/admin/content-types/new'
    | '/admin/offers/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/api/admin/offer-copy'
    | '/offers/preview/$id'
    | '/resources/$contentType/$pageSlug'
    | '/admin/content-types'
    | '/admin/offers'
    | '/admin/pages'
    | '/admin/pillars'
    | '/admin/posts'
    | '/resources/$contentType'
    | '/admin/content-types/$id/edit'
    | '/admin/offers/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/news'
    | '/offer-access'
    | '/privacy'
    | '/resources'
    | '/rss.xml'
    | '/shop'
    | '/sitemap'
    | '/sitemap.xml'
    | '/speaking'
    | '/start-here'
    | '/support'
    | '/terms'
    | '/admin/audience'
    | '/admin/categories'
    | '/admin/conversions'
    | '/admin/generate'
    | '/admin/inquiries'
    | '/admin/library'
    | '/admin/niches'
    | '/admin/pseo-dashboard'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/setup'
    | '/admin/site-settings'
    | '/admin/widgets'
    | '/admin_/login'
    | '/admin_/reset-password'
    | '/api/chat'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/news/$id'
    | '/newsletter/confirmed'
    | '/newsletter/invalid'
    | '/newsletter/unsubscribed'
    | '/offers/$slug'
    | '/resources/$contentType'
    | '/admin/'
    | '/blog/'
    | '/news/'
    | '/resources/'
    | '/admin/content-types/new'
    | '/admin/offers/new'
    | '/admin/pillars/new'
    | '/admin/posts/new'
    | '/api/admin/offer-copy'
    | '/offers/preview/$id'
    | '/resources/$contentType/$pageSlug'
    | '/admin/content-types/'
    | '/admin/offers/'
    | '/admin/pages/'
    | '/admin/pillars/'
    | '/admin/posts/'
    | '/resources/$contentType/'
    | '/admin/content-types/$id/edit'
    | '/admin/offers/$id/edit'
    | '/admin/pages/$id/edit'
    | '/admin/pillars/$id/edit'
    | '/admin/posts/$id/edit'
    | '/api/public/newsletter/confirm'
    | '/api/public/newsletter/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NewsRoute: typeof NewsRouteWithChildren
  OfferAccessRoute: typeof OfferAccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  RssDotxmlRoute: typeof RssDotxmlRoute
  ShopRoute: typeof ShopRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakingRoute: typeof SpeakingRoute
  StartHereRoute: typeof StartHereRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  NewsletterConfirmedRoute: typeof NewsletterConfirmedRoute
  NewsletterInvalidRoute: typeof NewsletterInvalidRoute
  NewsletterUnsubscribedRoute: typeof NewsletterUnsubscribedRoute
  OffersSlugRoute: typeof OffersSlugRoute
  ApiAdminOfferCopyRoute: typeof ApiAdminOfferCopyRoute
  OffersPreviewIdRoute: typeof OffersPreviewIdRoute
  ApiPublicNewsletterConfirmRoute: typeof ApiPublicNewsletterConfirmRoute
  ApiPublicNewsletterUnsubscribeRoute: typeof ApiPublicNewsletterUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-access': {
      id: '/offer-access'
      path: '/offer-access'
      fullPath: '/offer-access'
      preLoaderRoute: typeof OfferAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-here': {
      id: '/start-here'
      path: '/start-here'
      fullPath: '/start-here'
      preLoaderRoute: typeof StartHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audience': {
      id: '/admin/audience'
      path: '/audience'
      fullPath: '/admin/audience'
      preLoaderRoute: typeof AdminAudienceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversions': {
      id: '/admin/conversions'
      path: '/conversions'
      fullPath: '/admin/conversions'
      preLoaderRoute: typeof AdminConversionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generate': {
      id: '/admin/generate'
      path: '/generate'
      fullPath: '/admin/generate'
      preLoaderRoute: typeof AdminGenerateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/niches': {
      id: '/admin/niches'
      path: '/niches'
      fullPath: '/admin/niches'
      preLoaderRoute: typeof AdminNichesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pseo-dashboard': {
      id: '/admin/pseo-dashboard'
      path: '/pseo-dashboard'
      fullPath: '/admin/pseo-dashboard'
      preLoaderRoute: typeof AdminPseoDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/widgets': {
      id: '/admin/widgets'
      path: '/widgets'
      fullPath: '/admin/widgets'
      preLoaderRoute: typeof AdminWidgetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reset-password': {
      id: '/admin_/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/newsletter/confirmed': {
      id: '/newsletter/confirmed'
      path: '/newsletter/confirmed'
      fullPath: '/newsletter/confirmed'
      preLoaderRoute: typeof NewsletterConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/invalid': {
      id: '/newsletter/invalid'
      path: '/newsletter/invalid'
      fullPath: '/newsletter/invalid'
      preLoaderRoute: typeof NewsletterInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/unsubscribed': {
      id: '/newsletter/unsubscribed'
      path: '/newsletter/unsubscribed'
      fullPath: '/newsletter/unsubscribed'
      preLoaderRoute: typeof NewsletterUnsubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$contentType': {
      id: '/resources/$contentType'
      path: '/$contentType'
      fullPath: '/resources/$contentType'
      preLoaderRoute: typeof ResourcesContentTypeRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/admin/content-types/': {
      id: '/admin/content-types/'
      path: '/content-types'
      fullPath: '/admin/content-types/'
      preLoaderRoute: typeof AdminContentTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-types/new': {
      id: '/admin/content-types/new'
      path: '/content-types/new'
      fullPath: '/admin/content-types/new'
      preLoaderRoute: typeof AdminContentTypesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers/': {
      id: '/admin/offers/'
      path: '/offers'
      fullPath: '/admin/offers/'
      preLoaderRoute: typeof AdminOffersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers/new': {
      id: '/admin/offers/new'
      path: '/offers/new'
      fullPath: '/admin/offers/new'
      preLoaderRoute: typeof AdminOffersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pillars/': {
      id: '/admin/pillars/'
      path: '/pillars'
      fullPath: '/admin/pillars/'
      preLoaderRoute: typeof AdminPillarsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pillars/new': {
      id: '/admin/pillars/new'
      path: '/pillars/new'
      fullPath: '/admin/pillars/new'
      preLoaderRoute: typeof AdminPillarsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/offer-copy': {
      id: '/api/admin/offer-copy'
      path: '/api/admin/offer-copy'
      fullPath: '/api/admin/offer-copy'
      preLoaderRoute: typeof ApiAdminOfferCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/preview/$id': {
      id: '/offers/preview/$id'
      path: '/offers/preview/$id'
      fullPath: '/offers/preview/$id'
      preLoaderRoute: typeof OffersPreviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$contentType/': {
      id: '/resources/$contentType/'
      path: '/'
      fullPath: '/resources/$contentType/'
      preLoaderRoute: typeof ResourcesContentTypeIndexRouteImport
      parentRoute: typeof ResourcesContentTypeRoute
    }
    '/resources/$contentType/$pageSlug': {
      id: '/resources/$contentType/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/resources/$contentType/$pageSlug'
      preLoaderRoute: typeof ResourcesContentTypePageSlugRouteImport
      parentRoute: typeof ResourcesContentTypeRoute
    }
    '/admin/content-types/$id/edit': {
      id: '/admin/content-types/$id/edit'
      path: '/content-types/$id/edit'
      fullPath: '/admin/content-types/$id/edit'
      preLoaderRoute: typeof AdminContentTypesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers/$id/edit': {
      id: '/admin/offers/$id/edit'
      path: '/offers/$id/edit'
      fullPath: '/admin/offers/$id/edit'
      preLoaderRoute: typeof AdminOffersIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages/$id/edit': {
      id: '/admin/pages/$id/edit'
      path: '/pages/$id/edit'
      fullPath: '/admin/pages/$id/edit'
      preLoaderRoute: typeof AdminPagesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pillars/$id/edit': {
      id: '/admin/pillars/$id/edit'
      path: '/pillars/$id/edit'
      fullPath: '/admin/pillars/$id/edit'
      preLoaderRoute: typeof AdminPillarsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/newsletter/confirm': {
      id: '/api/public/newsletter/confirm'
      path: '/api/public/newsletter/confirm'
      fullPath: '/api/public/newsletter/confirm'
      preLoaderRoute: typeof ApiPublicNewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter/unsubscribe': {
      id: '/api/public/newsletter/unsubscribe'
      path: '/api/public/newsletter/unsubscribe'
      fullPath: '/api/public/newsletter/unsubscribe'
      preLoaderRoute: typeof ApiPublicNewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAudienceRoute: typeof AdminAudienceRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminConversionsRoute: typeof AdminConversionsRoute
  AdminGenerateRoute: typeof AdminGenerateRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminNichesRoute: typeof AdminNichesRoute
  AdminPseoDashboardRoute: typeof AdminPseoDashboardRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminWidgetsRoute: typeof AdminWidgetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentTypesNewRoute: typeof AdminContentTypesNewRoute
  AdminOffersNewRoute: typeof AdminOffersNewRoute
  AdminPillarsNewRoute: typeof AdminPillarsNewRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminContentTypesIndexRoute: typeof AdminContentTypesIndexRoute
  AdminOffersIndexRoute: typeof AdminOffersIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminPillarsIndexRoute: typeof AdminPillarsIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminContentTypesIdEditRoute: typeof AdminContentTypesIdEditRoute
  AdminOffersIdEditRoute: typeof AdminOffersIdEditRoute
  AdminPagesIdEditRoute: typeof AdminPagesIdEditRoute
  AdminPillarsIdEditRoute: typeof AdminPillarsIdEditRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAudienceRoute: AdminAudienceRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminConversionsRoute: AdminConversionsRoute,
  AdminGenerateRoute: AdminGenerateRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminNichesRoute: AdminNichesRoute,
  AdminPseoDashboardRoute: AdminPseoDashboardRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminWidgetsRoute: AdminWidgetsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentTypesNewRoute: AdminContentTypesNewRoute,
  AdminOffersNewRoute: AdminOffersNewRoute,
  AdminPillarsNewRoute: AdminPillarsNewRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminContentTypesIndexRoute: AdminContentTypesIndexRoute,
  AdminOffersIndexRoute: AdminOffersIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminPillarsIndexRoute: AdminPillarsIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminContentTypesIdEditRoute: AdminContentTypesIdEditRoute,
  AdminOffersIdEditRoute: AdminOffersIdEditRoute,
  AdminPagesIdEditRoute: AdminPagesIdEditRoute,
  AdminPillarsIdEditRoute: AdminPillarsIdEditRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ResourcesContentTypeRouteChildren {
  ResourcesContentTypePageSlugRoute: typeof ResourcesContentTypePageSlugRoute
  ResourcesContentTypeIndexRoute: typeof ResourcesContentTypeIndexRoute
}

const ResourcesContentTypeRouteChildren: ResourcesContentTypeRouteChildren = {
  ResourcesContentTypePageSlugRoute: ResourcesContentTypePageSlugRoute,
  ResourcesContentTypeIndexRoute: ResourcesContentTypeIndexRoute,
}

const ResourcesContentTypeRouteWithChildren =
  ResourcesContentTypeRoute._addFileChildren(ResourcesContentTypeRouteChildren)

interface ResourcesRouteChildren {
  ResourcesContentTypeRoute: typeof ResourcesContentTypeRouteWithChildren
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesContentTypeRoute: ResourcesContentTypeRouteWithChildren,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NewsRoute: NewsRouteWithChildren,
  OfferAccessRoute: OfferAccessRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  RssDotxmlRoute: RssDotxmlRoute,
  ShopRoute: ShopRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakingRoute: SpeakingRoute,
  StartHereRoute: StartHereRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  NewsletterConfirmedRoute: NewsletterConfirmedRoute,
  NewsletterInvalidRoute: NewsletterInvalidRoute,
  NewsletterUnsubscribedRoute: NewsletterUnsubscribedRoute,
  OffersSlugRoute: OffersSlugRoute,
  ApiAdminOfferCopyRoute: ApiAdminOfferCopyRoute,
  OffersPreviewIdRoute: OffersPreviewIdRoute,
  ApiPublicNewsletterConfirmRoute: ApiPublicNewsletterConfirmRoute,
  ApiPublicNewsletterUnsubscribeRoute: ApiPublicNewsletterUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
